PycharmProjects/Forum/Forum/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('forumapp.urls', namespace="forumapp")),
]

PycharmProjects/Forum/forumapp/urls.py
__author__ = 'discovery'
__author__ = 'discovery'
from django.conf.urls import url



from django.conf.urls import url



from . import views

# all url patterns
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$',views.VoteView.as_view(), name='vote'),
    url(r'^categories/$', views.CategoriesView.as_view(), name='categories'),
    url(r'^topic/(?P<question_id>\d+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^register/$', views.register, name='register'), # ADD NEW PATTERN
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    #url(r'^(?P<pk>[0-9]+)/vote/$', views.VotesView.as_view(), name='vote'),
]

PycharmProjects/Forum/forumapp/models.py
from django.db import models

# Create your models here.
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    #user_id =models.PositiveIntegerField(verbose_name="User ID")
    user_name = models.CharField(verbose_name="User Name", max_length=500)
    user_pass = models.CharField(verbose_name="Password", max_length=500)
    user_mail = models.EmailField(verbose_name="E-Mail", max_length=500)
    user_date = models.DateTimeField("Publish Date", auto_now_add=True)

    def __str__(self):
        return self.user_name

#Question models it has a name and date
class Categories(models.Model):
    #user = models.ForeignKey(User)
    #cat_id =models.PositiveIntegerField(verbose_name="Cat ID")
    cat_name = models.CharField(verbose_name="Categories", max_length=500)
    cat_description = models.CharField(verbose_name="Categories Description", max_length=500)
    pub_date = models.DateTimeField("Publish Date", auto_now_add=True)

    # this method get us Quesiton class name
    def __str__(self):
        return self.cat_name
    #property means call method like a variable
    #@property
    #def was_published_recently(self):
    #    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# Choice model it has a question relational , choice name and votes number
class Topics(models.Model):
    user = models.ForeignKey(User)
    categories = models.ForeignKey(Categories)
    #topic_id =models.PositiveIntegerField(verbose_name="Topic ID")
    topic_subject = models.CharField(verbose_name="Topic Subject", max_length=500)
    topic_date = models.DateTimeField("Publish Date", auto_now_add=True)
    #topic_cat =models.PositiveIntegerField(verbose_name="Topic Cat")
    #topic_by =models.PositiveIntegerField(verbose_name="Topic By")

    # this method get us Quesiton class name
    def __str__(self):
        return self.topic_subject


class Posts(models.Model):
    user = models.ForeignKey(User)
    topics = models.ForeignKey(Topics)
    #posts_id =models.PositiveIntegerField(verbose_name="Post ID")
    posts_content = models.CharField(verbose_name="Post Content", max_length=500)
    posts_date = models.DateTimeField("Post Date", auto_now_add=True)
    #posts_topic =models.PositiveIntegerField(verbose_name="Post Cat")
    #posts_by =models.PositiveIntegerField(verbose_name="Post By")

class Comment(models.Model):
    user= models.ForeignKey(User)

    comment= models.CharField(verbose_name="Comment ",max_length=500)

    # this method get us Quesiton class name



    #unicode is same _str_
    def __unicode__(self):
        return self.posts_content

PycharmProjects/Forum/forumapp/forms.py
__author__ = 'discovery'
__author__ = 'discovery'
from django import forms
from forumapp.models import Categories, Topics,User,Comment



class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        #form for questions text box date is auto
        fields = ['cat_name','cat_description']



class TopicsForm(forms.ModelForm):
    class Meta:
        model = Topics
        #form for choice
        fields = ['categories', 'topic_subject']

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('user_name', 'user_mail', 'user_pass')

PycharmProjects/Forum/forumapp/views.py
import profile
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404

# Create your views here.
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.views import generic
from django.views.generic import View
from forumapp.forms import CategoriesForm, TopicsForm,UserForm,CommentsForm
from forumapp.models import Categories, Topics,User

from django.contrib.auth.models import User
from django import forms



class IndexView(generic.ListView):

    model = Categories
    template_name = 'index.html'
    context_object_name = 'latest_categories_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Categories.objects.order_by('pub_date')


class DetailView(generic.DetailView):
    model = Categories
    template_name = 'category.html'




#Results view class for votes results
class ResultsView(generic.DetailView):
    model = Categories
    template_name = 'results.html'


# Question view for list all of Questions
class CategoriesView(View):
    # get method 
    def get(self, request):
        categories_form = CategoriesForm()
        return render(request, 'create_cat.html', {
            'categories_form': categories_form,
        })

    def post(self, request):
        categories_form = CategoriesForm(request.POST)
        if categories_form.is_valid():
            categories_form.save()
            return HttpResponseRedirect(reverse('forumapp:index'))
        else:
            return render(request, 'create_cat.html', {
                'categories_form': categories_form,
                'errors': categories_form.errors
            })

#Choice view for create a new choice
class TopicView(View):
    # get and post same part
    def dispatch(self, request, question_id, *args, **kwargs):
        self.categories = Categories.objects.get(pk=question_id)
        return super(TopicView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        choice_form = TopicsForm(initial={'categories': self.categories})
        return render(request, 'create_topic.html', {
            'categories': self.categories,
            'choice_form': choice_form,
        })

    def post(self, request, *args, **kwargs):
        choice_form = TopicsForm(request.POST, initial={'categories': self.categories})
        if choice_form.is_valid():
            choice_form.save()
            return HttpResponseRedirect(reverse('forumapp:index', args=(choice_form.cleaned_data.get('categories').pk,)))
        else:
            return render(request, 'create_topic.html', {
                'categories': self.categories,
                'choice_form': choice_form,
                'errors': choice_form.errors
            })


class CommentView(View):
    # get method
    def get(self, request):
        comment_form = CommentsForm()
        return render(request, 'create_cat.html', {
            'categories_form': comment_form,
        })

    def post(self, request):
        comment_form = CommentsForm(request.POST)
        if comment_form.is_valid():
            comment_form.save()
            return HttpResponseRedirect(reverse('forumapp:index'))
        else:
            return render(request, 'create_cat.html', {
                'categories_form': comment_form,
                'errors': comment_form.errors
            })
#Voteview for votes and post it
# get method are not using this view
# class VoteView(View):
#     def __init__(self):
#         self.output = ''
#
#     def dispatch(self, request, *args, **kwargs):
#         return super(VoteView, self).dispatch(request, *args, **kwargs)
#
#     def get(self, request, question_id):
#         raise Http404("Not Found")
#
#     def post(self, request, question_id, *args, **kwargs):
#         question = get_object_or_404(Question, pk=question_id)
#         try:
#             selected_choice = question.choice_set.get(pk=request.POST['choice'])
#         except (KeyError, Choice.DoesNotExist):
#             # Redisplay the question voting form.
#             return render(request, 'polls/detail.html', {
#                 'question': question,
#                 'error_message': "You didn't select a choice."
#             })
#         else:
#             selected_choice.votes += 1
#             selected_choice.save()
#             # Always return an HttpResponseRedirect after successfully dealing
#             # with POST data. This prevents data from being posted twice if a
#             # user hits the Back button.
#             return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)


        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.


            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.

            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()


    # Render the template depending on the context.
    return render_to_response(
            'register.html',
            {'user_form': user_form,'registered': registered},
            context)

PycharmProjects/Forum/forumapp/templates/category.html
  {% include "polls/../../../../Forum/forumapp/templates/import.html" %}
    <a href="{% url 'forumapp:topic' categories.pk %}">Create topic</a>

    <h2>{{ question.question_text }}</h2>
    <p> ********   Categories ******* <br/><br/>

    </p>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'forumapp:topic' categories.id %}" method="post">
    {% csrf_token %}
    {% for choice in categories.topics_set.all %}
        {{ choice.topic_subject }}<br/>
        {% for choice2 in choice.comments_set.all %}
             {{ choice2.comment }}

        {% endfor %}
        <br/><br/>
    {% endfor %}

    </form>

PycharmProjects/Forum/forumapp/templates/create_cat.html
 <h2 style="font-family: Arial">Add a Category</h2>



  {% if errors %}
    {% for key,error in errors.iteritems %}
      {{ key }}: {{ error }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="cat_name"></label>
        <h3>Category Name</h3>
        {{ categories_form.cat_name }}
        <h3>Category Description</h3>
        {{ categories_form.cat_description }}<br/><br/>

    <input type="submit" value="Save"/>
  </form>

PycharmProjects/Forum/forumapp/templates/create_topic.html
{% include "polls/../../../../Forum/forumapp/templates/import.html" %}

    <h2 style="font-family:Arial">Add a Topic</h2>

  {% if errors %}
        {% for key,error in errors.iteritems %}
          {{ key }}: {{ error }}
        {% endfor %}
      {% endif %}
      <form method="post">
        {% csrf_token %}

        <div style="color: #009FC1" >
          <label for="cat_name">Categories</label>
          {{ choice_form.categories }}
        </div></br></br>
        <div style="color: #032472">
          <label for="cat_name">Topic</label>
          {{ choice_form.topic_subject }}
        </div></br>
        <div >
            <input style="background-color: #dddbd7 ;font-size: larger ; color: #B40E1F"  type="submit" value="Save"/>
        </div></br>

      </form>

PycharmProjects/Forum/forumapp/templates/footer.html
<div id="footer">Copyrihts@</div>
</body>
</html>

PycharmProjects/Forum/forumapp/templates/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="nl" lang="nl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="description" content="A short description." />
	<meta name="keywords" content="put, keywords, here" />
	<title>G.T.U Forum</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
	<link rel="stylesheet" href="css/menu.css" type="text/css">
    <script src="js/jquery.min.js"></script>
    <script src="js/jquery.form-validator.min.js"></script>
</head>
<body>


	<div id="wrapper">
	
	<div id="logo">
	<table style="width:200px; float:left; ">
	<tr>
	<td><img  src="img/logo.png"  height="40" width="200"></td>
	<td><h1 style="float:left;">G.T.U</h1></td>
	</tr>
	</table>
	</div>
	
	<div id="menu">
	
		<ul class="menuTemplate3 decor3_1" license="mylicense">
		<li><a href="/forum/index.php">Home</a></li>
			<li class="separator"></li>
		<li><a href="/forum/create_topic.php">Create a topic</a></li>
					<li class="separator"></li>
		<li><a href="/forum/create_cat.php">Create a category</a></li>
		
		<div id="userbar">	
		<?php
 session_start();
 if(isset($_SESSION['signed_in'])){
   echo '<li style="margin-top:10px;">Welcome, ' . $_SESSION['user_name'] . '</li>. <li><a style="text-decoration: underline;" href="signout.php">Log Out</a></li>.';

	 
	 	}
 	else
 	{
 		echo '<li><a href="signin.php">Log In</a></li> <li class="separator"></li> <li><a href="signup.php">Create an account</a></li>.';
 	}
?>

		</div>
		</ul>

	

		

</div>
		<div id="content">
	

PycharmProjects/Forum/forumapp/templates/import.html
<div align="center">

    <a  style="display: inline-block" href="{% url 'forumapp:index' %}">Home Page   </a> || <a style="display: inline-block" href="{% url 'forumapp:categories' %}">   Create Category</a>


<body style="background: ../../../static/anket.jpj">

PycharmProjects/Forum/forumapp/templates/index.html
 {% include "polls/../../../../Forum/forumapp/templates/import.html" %}
<a href="{% url 'forumapp:register' %}">Register Here</a>

<div style="color: #009FC1">
    <h1 xmlns="http://www.w3.org/1999/html" style="font-family: Verdana">Welcome  My Blog </h1>
    <h2>Lets Begin </h2>
</div></br></br>


{% if latest_categories_list %}
    <ul>
    {% for category in latest_categories_list %}
        <li><a href="/{{ category.id }}/">{{ category.cat_name }}</a></li></br>
            <table><tr>
                <td>{{category.cat_name}}</td>
                <td>{{ category.cat_description }}</td>
            </tr></table>

        {% for choice in category.topics_set.all %}
            <li>{{ choice.topic_subject }}</li>
            <form method="post">
            {% csrf_token %}
            <label for="cat_name"></label>

                <h3>Category comments</h3>
                {{ comment_form.comments }}<br/><br/>

                <input type="submit" value="Save"/>

        {% endfor %}

    {% endfor %}
    </ul>

{% else %}

    <p>No Categories Posted Yet.</p>
{% endif %}


 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

PycharmProjects/Forum/forumapp/templates/logout.html
Logged out!

PycharmProjects/Forum/forumapp/templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>

    <body>
        <h1>Register</h1>

        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="/rango/">Return to the homepage.</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action="/rango/register/"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}


            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
    </body>
</html>

PycharmProjects/Forum/forumapp/templates/replyon.html
<?php
//create_cat.php
include 'connect.php';

include 'header.php';

if($_SERVER['REQUEST_METHOD'] != 'POST')
{
	//someone is calling the file directly, which we don't want
	echo 'This file cannot be called directly.';
}
else
{
	//check for sign in status
	if(!$_SESSION['signed_in'])
	{
		echo 'You must be signed in to post a reply.';
	}
	else
	{
		//a real user posted a real reply
		$sql = "INSERT INTO 
					posts(post_content,
						  post_date,
						  post_topic,
						  post_by) 
				VALUES ('" . $_POST['reply-content'] . "',
						NOW(),
						" . $con->real_escape_string($_GET['id']) . ",
						" . $_SESSION['user_id'] . ")";
						
		$result = $con->query($sql);
						
		if(!$result)
		{
			echo 'Your reply has not been saved, please try again later.';
		}
		else
		{
			echo 'Your reply has been saved, check out <a href="topic.php?id=' . htmlentities($_GET['id']) . '">the topic</a>.';
		}
	}
}

include 'footer.php';
?>

PycharmProjects/Forum/forumapp/templates/sigin.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

PycharmProjects/Forum/forumapp/templates/signup.html
<?php
//signup.php
include 'connect.php';
include 'header.php';


if($_SERVER['REQUEST_METHOD'] != 'POST')
{
    /*the form hasn't been posted yet, display it
	  note that the action="" will cause the form to post to the same page it is on */
	  echo '<h2>Sign up</h2>';
      echo '<form method="post" id="registration" action="">
	<table id="form-tb">
		<tr>
 	 	<td>Username:</td>
		<td><input type="text" name="user_name"  data-validation="length" data-validation-length="min5" data-validation-error-msg="User name has to be at least 5 characters long" /></td>
		</tr>
		<tr>
 		<td>Password:</td> 
		<td><input type="password" name="user_pass" data-validation="length" data-validation-length="min8" data-validation-error-msg="Password has to be at least 8 characters long" ></td>
		</tr>
		<tr>
		<td>Password again:</td> 
		<td><input type="password" name="user_pass_check" data-validation="length" data-validation-length="min8" data-validation-error-msg="Password has to be at least 8 characters long"></td>
		</tr>
		<tr>
		<td>E-mail:</td>
		<td><input type="email" name="user_email" data-validation="email" ></td>
		</tr>
		<tr>
		<td></td>
 		<td><input type="submit" value="Submit" /></td>
		</tr>
 	 </form>
	<script> $.validate({form : \'#registration\'}); </script>

	 ';
	 
}
else
{
    /* so, the form has been posted, we'll process the data in three steps:
		1.	Check the data
		2.	Let the user refill the wrong fields (if necessary)
		3.	Save the data 
	*/
	$errors = array(); /* declare the array for later use */
	
	if(isset($_POST['user_name']))
	{
		//the user name exists
		if(!ctype_alnum($_POST['user_name']))
		{
			$errors[] = 'The username can only contain letters and digits.';
		}
		if(strlen($_POST['user_name']) > 30)
		{
			$errors[] = 'The username cannot be longer than 30 characters.';
		}
	}
	else
	{
		$errors[] = 'The username field must not be empty.';
	}
	
	
	if(isset($_POST['user_pass']))
	{
		if($_POST['user_pass'] != $_POST['user_pass_check'])
		{
			$errors[] = 'The two passwords did not match.';
		}
	}
	else
	{
		$errors[] = 'The password field cannot be empty.';
	}
	
	if(!empty($errors)) /*check for an empty array, if there are errors, they're in this array (note the ! operator)*/
	{
		echo 'Uh-oh.. a couple of fields are not filled in correctly..';
		echo '<ul>';
		foreach($errors as $key => $value) /* walk through the array so all the errors get displayed */
		{
			echo '<li>' . $value . '</li>'; /* this generates a nice error list */
		}
		echo '</ul>';
	}
	else
	{
		//the form has been posted without, so save it
		//notice the use of mysql_real_escape_string, keep everything safe!
		//also notice the sha1 function which hashes the password
		$sql = "INSERT INTO
					users(user_name, user_pass, user_email ,user_date, user_level)
				VALUES('" . $con->real_escape_string($_POST['user_name']) . "',
					   '" . sha1($_POST['user_pass']) . "',
					   '" . $con->real_escape_string($_POST['user_email']) . "',
						NOW(),
						0)";
						
		$result = $con->query($sql);
		if(!$result)
		{
			//something went wrong, display the error
			echo 'Something went wrong while registering. Please try again later.';
			//echo mysql_error(); //debugging purposes, uncomment when needed
		}
		else
		{
			echo 'Successfully registered. You can now <a href="signin.php">sign in</a> and start posting! :-)';
		}
	}
}

include 'footer.php';
?>