PycharmProjects/django/DjangoStart/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

PycharmProjects/django/polls/urls.py
__author__ = 'discovery'
from django.conf.urls import url



from django.conf.urls import url



from . import views

# all url patterns
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.VoteView.as_view(), name='vote'),
    url(r'^question/$', views.QuestionView.as_view(), name='question'),
    url(r'^choice/(?P<question_id>\d+)/$', views.ChoiceView.as_view(), name='choice'),
    #url(r'^(?P<pk>[0-9]+)/vote/$', views.VotesView.as_view(), name='vote'),
]

PycharmProjects/django/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

#Question models it has a name and date
class Question(models.Model):
    question_text = models.CharField(verbose_name="Question", max_length=500)
    pub_date = models.DateTimeField("Publish Date", auto_now_add=True)

    # this method get us Quesiton class name
    def __str__(self):
        return self.question_text
    #property means call method like a variable
    @property
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# Choice model it has a question relational , choice name and votes number
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    #unicode is same _str_
    def __unicode__(self):
        return self.choice_text

PycharmProjects/django/polls/models/Choice.py
__author__ = 'discovery'

PycharmProjects/django/polls/models/Question.py
__author__ = 'discovery'

PycharmProjects/django/polls/forms.py
__author__ = 'discovery'
from django import forms
from polls.models import Question, Choice



class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        #form for questions text box date is auto
        fields = ['question_text']



class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        #form for choice
        fields = ['question', 'choice_text']

PycharmProjects/django/polls/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import View
from polls.forms import QuestionForm, ChoiceForm
from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'




#Results view class for votes results
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# Question view for list all of Questions
class QuestionView(View):
    # get method 
    def get(self, request):
        question_form = QuestionForm()
        return render(request, 'polls/addQuestion.html', {
            'question_form': question_form,
        })

    def post(self, request):
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question_form.save()
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            return render(request, 'polls/addQuestion.html', {
                'question_form': question_form,
                'errors': question_form.errors
            })

#Choice view for create a new choice
class ChoiceView(View):
    # get and post same part
    def dispatch(self, request, question_id, *args, **kwargs):
        self.question = Question.objects.get(pk=question_id)
        return super(ChoiceView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        choice_form = ChoiceForm(initial={'question': self.question})
        return render(request, 'polls/addChoice.html', {
            'question': self.question,
            'choice_form': choice_form,
        })

    def post(self, request, *args, **kwargs):
        choice_form = ChoiceForm(request.POST, initial={'question': self.question})
        if choice_form.is_valid():
            choice_form.save()
            return HttpResponseRedirect(reverse('polls:detail', args=(choice_form.cleaned_data.get('question').pk,)))
        else:
            return render(request, 'polls/addChoice.html', {
                'question': self.question,
                'choice_form': choice_form,
                'errors': choice_form.errors
            })

#Voteview for votes and post it
# get method are not using this view
class VoteView(View):
    def __init__(self):
        self.output = ''

    def dispatch(self, request, *args, **kwargs):
        return super(VoteView, self).dispatch(request, *args, **kwargs)

    def get(self, request, question_id):
        raise Http404("Not Found")

    def post(self, request, question_id, *args, **kwargs):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice."
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

PycharmProjects/django/polls/templates/polls/addChoice.html
{% include "polls/../../../../Forum/forumapp/templates/import.html" %}

    <h2 style="font-family:Arial">Add a Choice</h2>

      {% if errors %}
        {% for key,error in errors.iteritems %}
          {{ key }}: {{ error }}
        {% endfor %}
      {% endif %}
      <form method="post">
        {% csrf_token %}

        <div style="color: #009FC1" >
          <label for="question_text">Question</label>
          {{ choice_form.question }}
        </div></br></br>
        <div style="color: #032472">
          <label for="question_text">Choice</label>
          {{ choice_form.choice_text }}
        </div></br>
        <div >
            <input style="background-color: #dddbd7 ;font-size: larger ; color: #B40E1F"  type="submit" value="Save"/>
        </div></br>

      </form>



{% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

PycharmProjects/django/polls/templates/polls/addQuestion.html
{% include "polls/../../../../Forum/forumapp/templates/import.html" %}



  <h2 style="font-family: Arial">Add a Question</h2>



  {% if errors %}
    {% for key,error in errors.iteritems %}
      {{ key }}: {{ error }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="question_text">Question</label>
    {{ question_form.question_text }}
    <input type="submit" value="Save"/>
  </form>



{% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

PycharmProjects/django/polls/templates/polls/index.html
 {% include "polls/../../../../Forum/forumapp/templates/import.html" %}


<div style="color: #009FC1">
    <h1 xmlns="http://www.w3.org/1999/html" style="font-family: Verdana">Welcome  Questionnaire </h1>
    <h2>Lets Begin </h2>
</div></br></br>

<p> Please Choice a Question and Press
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/{{ question.id }}/">{{ question.question_text }}</a></li></br>
    {% endfor %}
    </ul>

{% else %}

    <p>No polls are available.</p>
{% endif %}

</p>
 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %}

PycharmProjects/django/polls/templates/polls/menu.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'polls/menu.css' %}" />

<div id="menu">

		<ul class="menuTemplate3 decor3_1" license="mylicense">
		<li><a href="{% url 'polls:index' %}">Home Page</a></li>
			<li class="separator"></li>
		<li><a href="{% url 'polls:question' %}">Create Question</a></li>
					<li class="separator"></li>

		</ul>
    </div>

PycharmProjects/django/polls/templates/polls/results.html
 {% include "polls/../../../../Forum/forumapp/templates/import.html" %}<!– import up page  –>


<h1>{{ question.question_text }}</h1>

<ol>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li><br/><br/>
{% endfor %}
</ol>

<br/><a href="{% url 'polls:detail' question.id %}">Do You Wanna Vote Again?</a>


 {% include "polls/../../../../Forum/forumapp/templates/downPage.html" %} <!– import down  page  –>